#ifndef LIBPGFE_META_H
#define LIBPGFE_META_H

#define LIBPGFE_NAME "libpgfe"

#define LIBPGFE_MAJOR_VERSION 0
#define LIBPGFE_MINOR_VERSION 1
#define LIBPGFE_REVISION 0

#define LIBPGFE_VERSION "0.1.0"
#endif
