#ifndef LIBPGFE_VERSION_H
#define LIBPGFE_VERSION_H

#define LIBPGFE_MAJOR_VERSION 0
#define LIBPGFE_MINOR_VERSION 7
#define LIBPGFE_REVISION 2
#define LIBPGFE_VARIANT ""

#define LIBPGFE_VERSION "0.7.2"

#endif
