#ifndef LIBPGFE_VERSION_H
#define LIBPGFE_VERSION_H

#define LIBPGFE_MAJOR_VERSION 0
#define LIBPGFE_MINOR_VERSION 5
#define LIBPGFE_REVISION 1
#define LIBPGFE_VARIANT "dev"

#define LIBPGFE_VERSION "0.5.1-dev"

#endif
