#ifndef LIBPGFE_VERSION_H
#define LIBPGFE_VERSION_H

#define LIBPGFE_MAJOR_VERSION 0
#define LIBPGFE_MINOR_VERSION 6
#define LIBPGFE_REVISION 0
#define LIBPGFE_VARIANT "dev"

#define LIBPGFE_VERSION "0.6.0-dev"

#endif
